### PR TITLE
prepare for move to puppet-community

### PR DESCRIPTION
**Pull request by ryanycoleman**
During the Gent contributors summit, the future of puppetlabs-mcollective was called into questions. Admitting that Puppet Labs has a lot of modules to maintain and with PE, we're not the primary users of open-source MCollective, it makes more sense for the puppet-community to own the mcollective module. This will enable more community members who run FOSS MCollective in production to contribute to the management module for it. 

Decided on by ryanycoleman with acknowledgment by @mhaskel & @nibalizer. 

This PR alone will not get the job done. The work to transfer this module includes.
- [x] Replace README with warning on transfer
- [x] Update metadata.json with information on the new author
- [ ] Transfer the GitHub repository to the puppet-community organization
- [ ] Publish the 99.99.99 version from the puppet-community GitHub organization to the 'puppet' Forge namespace

Do not merge unless you are going to coordinate the logistics of the final two actions in addition to hitting merge.

### CODE REVIEW

**Comment by nibalizer** [comment]
I can coordinate from the puppet-community side when we're ready to do this.

**Comment by nibalizer** [comment]
Whats our status on this one?

**Comment by cmurphy** [comment]
> Publish the 99.99.99 version from the puppet-community GitHub organization to the 'puppet' Forge namespace

Shouldn't this version be published from the puppetlabs GitHub organization to the 'puppetlabs' forge namespace? Then the puppet-community org and the puppet namespace can continue with versioning as normal. I can help coordinate on that end.

**Comment by nibalizer** [comment]
Agree with @cmurphy

**Comment by cmurphy** [comment]
Closed via #197, will make the release and transfer on Tuesday March 24.

**Pull request closed without merging**
